### PR TITLE
Refactoring & convert to syncro

### PR DESCRIPTION
**Pull request by deltazerorsan**
This is a revised, simplified and refactoriced versión, separate into tabs and convert the program to a synchronous run mode. It also has a cron.

### CODE REVIEW

**Comment by SensorsIot** [comment]
Nice job! I am testing it with my various clocks here and merge it when it works. One thing I discovered is that the Wi-Fi time to connect is much too short for my installation. I changed it ti 500 ms and 20 turns.

**Comment by SensorsIot** [comment]
I just played around with it. I am not sure if you are too tight with sending signals. For example, if I set up a new clock (battery change, for example), I would like to synchronize it right away. This could be done by checking the reset cause and send signals after reset of the ESP right away.
Then I am not sure if it is a good idea to just send one single signal. Because, if the clock is out of sync, it will never sync because it expects a signal all the time and stops searching after a few minutes. Or if it does not get the signal the first time, it also never will sync.
What do you think?

**Comment by deltazerorsan** [comment]
Hi Andreas,

Yes you are right, but you can compile the sketch uncommenting the line (29)

// #define TESTMODE       // Uncomment this line to bypass de cron and have the transmitter on all the time

and it runs all the time.

There also the possibility to add a button to override the cron and awake the ESP32 at same time....

That's software!

I hope it runs well with your Ikea clock or any chinese movement but I have some trouble with the German Junghans Alarm clocks, that run smoothly with the raspi version... Don't know why...

One of the most important things to note about this version is the confidence of the RTC inside the ESP32, I have some clocks around, ESP^32 based, calling earth only one time a day and they are very precise down the second.

Roman

**Comment by deltazerorsan** [comment]
mmm, it seems a good idea to check for reset reason and react to the reset button or power reset overriding cron, but, How much time? 10 minutes?

**Comment by SensorsIot** [comment]
I would say at least 10 minutes. It takes quite a long time to synchronize. My question is: After some reasoning, my question is: Why switch it off in general? It only consumes a few mA and can create problems with clocks who lost synchronization? It should at least have an option to leave it on for all people who do not want the hassle.

**Comment by SensorsIot** [comment]
Hi Roman,

Just saw your mail (after commenting github). I would change then the “test mode” in continuaous mode.
So far I did not test it on my “live” ESP. But now I will do it in test mode.

Regards
Andreas

Von: Rsan <notifications@github.com>
Gesendet: Donnerstag, 9. Januar 2020 08:55
An: SensorsIot/DCF77-Transmitter-for-ESP32 <DCF77-Transmitter-for-ESP32@noreply.github.com>
Cc: Andreas Spiess <andreas.spiess@arumba.com>; Comment <comment@noreply.github.com>
Betreff: Re: [SensorsIot/DCF77-Transmitter-for-ESP32] Refactoring & convert to syncro (#2)


Hi Andreas,

Yes you are right, but you can compile the sketch uncommenting the line (29)

// #define TESTMODE // Uncomment this line to bypass de cron and have the transmitter on all the time

and it runs all the time.

There also the possibility to add a button to override the cron and awake the ESP32 at same time....

That's software!

I hope it runs well with your Ikea clock or any chinese movement but I have some trouble with the German Junghans Alarm clocks, that run smoothly with the raspi version... Don't know why...

One of the most important things to note about this version is the confidence of the RTC inside the ESP32, I have some clocks around, ESP^32 based, calling earth only one time a day and they are very precise down the second.

Roman

**Comment by deltazerorsan** [comment]
ok, let me know your progress!

**Comment by SensorsIot** [comment]
It works in test mode. The clock took 6 Minutes to synchronize...
Maybe you could change the name of the test mode and add a little text to it? Adding the reboot functionality seems to be needed, and maybe an additional button if somebody wants.

I will then merge it. I quickly tried it before with wakeup reason 0 and it worked...
Keep in mind that the first time cannot be used by the clock as, after reset, the transmitter starts somewhere in the middle.

**Comment by deltazerorsan** [comment]
Ok, will work on it...

> Keep in mind that the first time cannot be used by the clock as, after reset, the transmitter starts somewhere in the middle.

Yes but is almost the same in any wake up. Will take a closer look.

Everything related to cron, stop it, minimum time... I run it on batteries and walk alongside every clock in the house... :-)

**Comment by SensorsIot** [comment]
Batteries are a good argument. But then, the reboot option would be handy...

**Comment by deltazerorsan** [comment]
Hope it's enough with the 10 minutes continuous work after reset. Another button seems not to be necessary.

The completely continuous mode is still there.

**Comment by SensorsIot** [comment]
I merged your version now. I did not look into your final code, but you could create a constant for the "ontime after reset" which then could be extended if a clock needs more time.

Thank you for your work!

**Comment by deltazerorsan** [comment]
Nice, will add the constant...

**Pull request merged**
